In [1]:
from datascience import *
import random
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

In [ ]:
!pip install uszipcode

In [45]:
sample_size = 500
incidents_for_year = {}
for year in np.arange(2018, 2023):
    url = (
        f"https://data.sfgov.org/resource/wg3w-h783.csv?"
        f"incident_year={year}&"
        f"$select=incident_category,Latitude,Longitude&"
        f"$where=Latitude%20IS%20NOT%20NULL&"
        f"$limit=50000"
    )
    incidents_for_year[year] = (Table.read_table(url)
                                     .sample(sample_size, 
                                             with_replacement=False))

In [46]:
incidents_for_year[2020]

incident_category           | Latitude | Longitude
Motor Vehicle Theft         | 37.787   | -122.4
Assault                     | 37.7932  | -122.393
Other Miscellaneous         | 37.7655  | -122.411
nan                         | 37.7538  | -122.419
Larceny Theft               | 37.753   | -122.406
Motor Vehicle Theft         | 37.7762  | -122.421
Malicious Mischief          | 37.7886  | -122.414
Miscellaneous Investigation | 37.7859  | -122.42
Non-Criminal                | 37.7864  | -122.408
Burglary                    | 37.8241  | -122.373
... (490 rows omitted)

In [47]:
url_2011 = (
    f"https://data.sfgov.org/resource/tmnf-yvry.csv?"
    f"date=2011-01-01T00:00:00.000&"
    f"$select=date,category,y,x&"
    f"$where=y%20IS%20NOT%20NULL&"
    f"$limit=50000")
table_2011 = Table.read_table(url_2011)
table_2011 = table_2011.drop("date")

url_2012 = (
    f"https://data.sfgov.org/resource/tmnf-yvry.csv?"
    f"date=2012-01-01T00:00:00.000&"
    f"$select=date,category,y,x&"
    f"$where=y%20IS%20NOT%20NULL&"
    f"$limit=50000")
table_2012 = Table.read_table(url_2012)
table_2012 = table_2012.drop("date")

url_2013 = (
    f"https://data.sfgov.org/resource/tmnf-yvry.csv?"
    f"date=2013-01-01T00:00:00.000&"
    f"$select=date,category,y,x&"
    f"$where=y%20IS%20NOT%20NULL&"
    f"$limit=50000")
table_2013 = Table.read_table(url_2013)
table_2013 = table_2013.drop("date")

url_2014 = (
    f"https://data.sfgov.org/resource/tmnf-yvry.csv?"
    f"date=2014-01-01T00:00:00.000&"
    f"$select=date,category,y,x&"
    f"$where=y%20IS%20NOT%20NULL&"
    f"$limit=50000")
table_2014 = Table.read_table(url_2014)
table_2014 = table_2014.drop("date")

url_2015 = (
    f"https://data.sfgov.org/resource/tmnf-yvry.csv?"
    f"date=2015-01-01T00:00:00.000&"
    f"$select=date,category,y,x&"
    f"$where=y%20IS%20NOT%20NULL&"
    f"$limit=50000")
table_2015 = Table.read_table(url_2015)
table_2015 = table_2015.drop("date")

url_2016 = (
    f"https://data.sfgov.org/resource/tmnf-yvry.csv?"
    f"date=2016-01-01T00:00:00.000&"
    f"$select=date,category,y,x&"
    f"$where=y%20IS%20NOT%20NULL&"
    f"$limit=50000")
table_2016 = Table.read_table(url_2016)
table_2016 = table_2016.drop("date")

url_2017 = (
    f"https://data.sfgov.org/resource/tmnf-yvry.csv?"
    f"date=2017-01-01T00:00:00.000&"
    f"$select=date,category,y,x&"
    f"$where=y%20IS%20NOT%20NULL&"
    f"$limit=50000")
table_2017 = Table.read_table(url_2017)
table_2017 = table_2017.drop("date")

incidents_for_year[2011] = table_2011.sample(500, with_replacement=False)
incidents_for_year[2012] = table_2012.sample(500, with_replacement=False)
incidents_for_year[2013] = table_2013.sample(500, with_replacement=False)
incidents_for_year[2014] = table_2014.sample(500, with_replacement=True)
incidents_for_year[2015] = table_2015.sample(500, with_replacement=False)
incidents_for_year[2016] = table_2016.sample(500, with_replacement=False)
incidents_for_year[2017] = table_2017.sample(500, with_replacement=True)

In [51]:
# A function taken from uszipcode documentation to search for latitude and longitude and outputs the zipcode
from uszipcode import SearchEngine

def lat_lng_to_zip(lat, lng):
    # Initialize the Search Engine 
    search = SearchEngine()

    # Search for the zipcode based on latitude and longitude 
    result = search.by_coordinates(lat, lng, radius = 1, returns = 1)

    # Check if a result is found 
    if result:
        # Extract the zip code from result 
        zipcode = result[0].zipcode

        # Check if the zipcode is within San Francisco (starts with "941")
        if zipcode.startswith("941"):
            return zipcode 
    return "Not in San Francisco"

def convert_zip_2011_2017(table):
    zip_from_latlong_array = make_array()
    for i in np.arange(table.num_rows):
        zip_from_latlong = lat_lng_to_zip(table.column("y").item(i), table.column("x").item(i))
        zip_from_latlong_array = np.append(zip_from_latlong_array, zip_from_latlong)
    converted_table = table.drop("y", "x").with_column("zip code", zip_from_latlong_array)
    return converted_table

In [52]:
report_2011 = convert_zip_2011_2017(incidents_for_year[2011])
report_2012 = convert_zip_2011_2017(incidents_for_year[2012])
report_2013 = convert_zip_2011_2017(incidents_for_year[2013])
report_2014 = convert_zip_2011_2017(incidents_for_year[2014])
report_2015 = convert_zip_2011_2017(incidents_for_year[2015])
report_2016 = convert_zip_2011_2017(incidents_for_year[2016])
report_2017 = convert_zip_2011_2017(incidents_for_year[2017])

In [58]:
report_2011.to_csv('incidents_for_year_2011.csv')
report_2012.to_csv('incidents_for_year_2012.csv')
report_2013.to_csv('incidents_for_year_2013.csv')
report_2014.to_csv('incidents_for_year_2014.csv')
report_2015.to_csv('incidents_for_year_2015.csv')
report_2016.to_csv('incidents_for_year_2016.csv')
report_2017.to_csv('incidents_for_year_2017.csv')

In [62]:
def convert_zip_2018_2022(table):
    zip_from_latlong_array = make_array()
    for i in np.arange(table.num_rows):
        zip_from_latlong = lat_lng_to_zip(table.column("Latitude").item(i), table.column("Longitude").item(i))
        zip_from_latlong_array = np.append(zip_from_latlong_array, zip_from_latlong)
    converted_table = table.drop("Latitude", "Longitude").relabel("incident_category", "category").with_column("zip code", zip_from_latlong_array)
    return converted_table

In [63]:
report_2018 = convert_zip_2018_2022(incidents_for_year[2018])
report_2019 = convert_zip_2018_2022(incidents_for_year[2019])
report_2020 = convert_zip_2018_2022(incidents_for_year[2020])
report_2021 = convert_zip_2018_2022(incidents_for_year[2021])
report_2022 = convert_zip_2018_2022(incidents_for_year[2022])

In [68]:
report_2018.to_csv('incidents_for_year_2018.csv')
report_2019.to_csv('incidents_for_year_2019.csv')
report_2020.to_csv('incidents_for_year_2020.csv')
report_2021.to_csv('incidents_for_year_2021.csv')
report_2022.to_csv('incidents_for_year_2022.csv')

In [ ]:
# from datetime import datetime

# def extract_date_components(date_str):
#     date_obj = datetime.strptime(date_str, "%Y-%m-%dT%H:%M:%S.%f")
#     year = date_obj.year
#     month = date_obj.month
#     day = date_obj.day
#     return year, month, day

# url_2 = (
#     f"https://data.sfgov.org/resource/tmnf-yvry.csv?"
#     #f"$where=date%20>=%20'2011-01-01T00:00:00.000'&"
#     f"$select=date,category,y,x&"
#     f"$where=y%20IS%20NOT%20NULL&"
#     f"$limit=700000")
# test = Table.read_table(url_2)
# year, month, day = zip(*test.apply(extract_date_components, 'date'))
# test = test.with_columns(
#          'Year', year,
#          'Month', month,
#          'Day', day)

# random.seed(56)
# year_2011 = test.where("Year", are.equal_to(2011)).sample(500, 
#                                               with_replacement=True).select("category","y", "x")
# year_2012 = test.where("Year", are.equal_to(2012)).sample(500, 
#                                               with_replacement=True).select("category","y", "x")
# year_2013 = test.where("Year", are.equal_to(2013)).sample(500, 
#                                               with_replacement=True).select("category","y", "x")
# year_2014 = test.where("Year", are.equal_to(2014)).sample(500, 
#                                               with_replacement=True).select("category","y", "x")
# year_2015 = test.where("Year", are.equal_to(2015)).sample(500, 
#                                               with_replacement=True).select("category","y", "x")
# year_2016 = test.where("Year", are.equal_to(2016)).sample(500, 
#                                               with_replacement=True).select("category","y", "x")
# year_2017 = test.where("Year", are.equal_to(2017)).sample(500, 
#                                               with_replacement=True).select("category","y", "x")